python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts 

# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/gaussian_blur/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type gaussian_blur_r
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/gaussian_noise/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type gaussian_std
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/jpeg/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type jpeg_ratio
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/rotate/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type random_rotate_ratio
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/distort/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type resize_ratio
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/crop/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type random_crop_ratio
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/brightness/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type brightness_factor
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/gamma/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type gamma
# python extract_wm.py --model_path runwayml/stable-diffusion-v1-5 --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/equalize/wm --wm_ground_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts --attack_type equalize