python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --output_path ./output/user_custom/ 

python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/gaussian_blur/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type gaussian_blur_r --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/gaussian_noise/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type gaussian_std --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/jpeg/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type jpeg_ratio --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/rotate/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type random_rotate_ratio --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/distort/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type resize_ratio --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/crop/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type random_crop_ratio --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/brightness/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type brightness_factor --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/gamma/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type gamma --output_path ./output/user_custom/
python extract_wm.py --model_path Lykon/AbsoluteReality --with_tracking --guidance_scale 8.5 --fpr 0.01 --channel_copy 1 --hw_copy 8 --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/equalize/wm --wm_ground_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type equalize --output_path ./output/user_custom/