python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/wm --no_wm_dir data/no_wm --prompt_dir data/prompts

python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/gaussian_blur/wm --no_wm_dir data/attack/gaussian_blur/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type gaussian_blur_r
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/gaussian_noise/wm --no_wm_dir data/attack/gaussian_noise/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type gaussian_std
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/jpeg/wm --no_wm_dir data/attack/jpeg/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type jpeg_ratio
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/rotate/wm --no_wm_dir data/attack/rotate/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type random_rotate_ratio
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/distort/wm --no_wm_dir data/attack/distort/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type resize_ratio
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/crop/wm --no_wm_dir data/attack/crop/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type random_crop_ratio
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/brightness/wm --no_wm_dir data/attack/brightness/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type brightness_factor
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/gamma/wm --no_wm_dir data/attack/gamma/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type gamma
python extract_wm.py --model_id runwayml/stable-diffusion-v1-5 --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/attack/equalize/wm --no_wm_dir data/attack/equalize/no_wm --wm_ground_dir data/wm --no_wm_ground_dir data/no_wm --prompt_dir data/prompts --attack_type equalize