python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/wm --no_wm_dir data/user_custom/no_wm --prompt_dir data/prompts --output_path ./output/user_custom/

python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/gaussian_blur/wm --no_wm_dir data/user_custom/attack/gaussian_blur/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type gaussian_blur_r --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/gaussian_noise/wm --no_wm_dir data/user_custom/attack/gaussian_noise/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type gaussian_std --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/jpeg/wm --no_wm_dir data/user_custom/attack/jpeg/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type jpeg_ratio --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/rotate/wm --no_wm_dir data/user_custom/attack/rotate/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type random_rotate_ratio --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/distort/wm --no_wm_dir data/user_custom/attack/distort/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type resize_ratio --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/crop/wm --no_wm_dir data/user_custom/attack/crop/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type random_crop_ratio --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/brightness/wm --no_wm_dir data/user_custom/attack/brightness/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type brightness_factor --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/gamma/wm --no_wm_dir data/user_custom/attack/gamma/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type gamma --output_path ./output/user_custom/
python extract_wm.py --model_id Lykon/AbsoluteReality --run_name no_attack --w_channel 1 --w_pattern ring --w_radius 3 --w_pattern_const 1.5 --guidance_scale 8.5 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --wm_dir data/user_custom/attack/equalize/wm --no_wm_dir data/user_custom/attack/equalize/no_wm --wm_ground_dir data/user_custom/wm --no_wm_ground_dir data/user_custom/no_wm --prompt_dir data/prompts --attack_type equalize --output_path ./output/user_custom/